[5_1_11_release_documentation] 5 1 11 release documentation
draios/onprem-install-docs pull request #91
Opened 2023-09-11 18:58 UTC by mvalin

### Basic info

- **JIRA issue**: https://sysdig.atlassian.net/browse/5_1_11_release_documentation

### Description

- Add Release History to link public document here
- Change the version and date
- Duplicate directory 5.1.10 as 5.1.11

2023-09-12 20:31 UTC, radhikapc commented on 5.1/5.1.11/examples/rbac/README.md
> +# RBAC for Installer (work in progress) v0.0.0a
```suggestion
# RBAC for Installer v0.0.0a ((work in progress) 
```

2023-09-12 20:32 UTC, radhikapc requested changes
nits

2023-09-12 22:21 UTC, radhikapc approved these changes
LGTM

2023-09-13 08:48 UTC, figarocorso approved these changes
LGTM

2023-09-13 13:53 UTC, merged